import { z } from "zod";

export const FlightNumberRequestSchema = z.object({
  query: z.string(),
});

export const FlightNumberResponseItem = z.object({
  value: z.object({
    _index: z.string(),
    _type: z.string(),
    _id: z.string(),
    _score: z.number(),
    _source: z.object({
      flightId: z.number(),
      hubUrl: z.string(),
      classification: z.number(),
      keywords: z.string(),
      lastUpdated: z.string(),
      creator: z.string(),
      creationDate: z.string(),
      carrier: z.string(),
      carrierIata: z.string(),
      carrierIcao: z.string(),
      carrierName: z.string(),
      flightNumber: z.string(),
      status: z.string(),
      codeshares: z.array(z.any()),
      departureAirport: z.string(),
      departureTimeZone: z.string(),
      departureAirportName: z.string(),
      departureAirportCity: z.string(),
      arrivalAirport: z.string(),
      arrivalTimeZone: z.string(),
      arrivalAirportName: z.string(),
      arrivalAirportCity: z.string(),
      departureDateTime: z.string(),
      publishedDeparture: z.string(),
      scheduledGateDeparture: z.string(),
      arrivalDateTime: z.string(),
      publishedArrival: z.string(),
      scheduledGateArrival: z.string(),
      arrivalTerminal: z.string().nullable(),
      scheduledEquipment: z.string(),
      recordStatus: z.string(),
      baggage: z.string().nullable(),
      id: z.null().optional(),
      wetlease: z.any().nullable(),
      tailNumber: z.string().nullable(),
      departure: z.any().nullable(),
      arrival: z.any().nullable(),
      delayMinutesDeparture: z.number().nullable(),
      delayMinutesArrival: z.number().nullable(),
      estimatedGateDeparture: z.string().nullable(),
      actualGateDeparture: z.string().nullable(),
      scheduledRunwayDeparture: z.string().nullable(),
      estimatedRunwayDeparture: z.string().nullable(),
      actualRunwayDeparture: z.string().nullable(),
      estimatedGateArrival: z.string().nullable(),
      actualGateArrival: z.string().nullable(),
      scheduledRunwayArrival: z.string().nullable(),
      estimatedRunwayArrival: z.string().nullable(),
      actualRunwayArrival: z.string().nullable(),
      departureGate: z.string().nullable(),
      arrivalGate: z.string().nullable(),
      actualEquipment: z.string().nullable(),
      actualEquipmentIcao: z.string().nullable(),
    }),
  }),
  stringLabel: z.boolean(),
  objectLabel: z.object({
    searchResultMainText: z.string(),
    searchSubText: z.string(),
    inputDisplayValue: z.string(),
    secondaryResultText: z.object({
      mainIconName: z.string(),
      primary: z.object({
        first: z.string(),
        second: z.string(),
        image: z.string(),
        third: z.string(),
      }),
      secondary: z.object({
        first: z.string(),
        second: z.string(),
        image: z.string(),
        third: z.string(),
      }),
    }),
  }),
});

export const FlightNumberResponseSchema = z.array(FlightNumberResponseItem);

export const TrackFlightRequestSchema = z.object({
  flightId: z.number(),
  airline: z.string(),
  flightNumber: z.string(),
  limit: z.string().nullable(),
});

const AirportSchema = z.object({
  fsCode: z.string(),
  name: z.string(),
  city: z.string(),
  countryCode: z.string(),
  countryName: z.string(),
  localTime: z.string(),
  latitude: z.number(),
  longitude: z.number(),
  elevationFt: z.number(),
  stateCode: z.string().optional(),
  conditions: z.string().optional(),
  temperatureCelsius: z.number().optional(),
  conditionIcon: z.string().optional(),
});

const FlightPositionSchema = z.object({
  lon: z.number(),
  lat: z.number(),
  speedMph: z.number(),
  altitudeFt: z.number(),
  source: z.string(),
  date: z.string(),
  course: z.number(),
  vrateMps: z.number(),
  lastObserved: z.string(),
});

export const TrackFlightResponseSchema = z.object({
  responseTime: z.number(),
  flightId: z.string(),
  carrierFs: z.string(),
  carrierFlightId: z.string(),
  carrierName: z.string(),
  operatedByFlightNum: z.string(),
  statusCode: z.string(),
  statusName: z.string(),
  statusColor: z.string(),
  statusAppendKey: z.string(),
  statusAppend: z.string(),
  flightEquipmentIata: z.string(),
  flightEquipmentName: z.string(),
  airports: z.object({
    departure: AirportSchema,
    arrival: AirportSchema,
    diverted: AirportSchema,
  }),
  bearing: z.number(),
  heading: z.number(),
  flightStatus: z.string(),
  operationalTimes: z.object({
    isActualDeparture: z.boolean(),
    utc: z.object({
      departureTime: z.number(),
      departureTimeString: z.string(),
      arrivalTime: z.number(),
      arrivalTimeString: z.string(),
      actualRunwayArrivalTime: z.number().nullable(),
      actualRunwayArrivalTimeString: z.string().nullable(),
      actualRunwayDepartureTime: z.number().nullable(),
      actualRunwayDepartureTimeString: z.string().nullable(),
    }),
    local: z.object({
      departureTime: z.number(),
      departureTimeString: z.string(),
      arrivalTime: z.number(),
      arrivalTimeString: z.string(),
      actualRunwayArrivalTime: z.number().nullable(),
      actualRunwayArrivalTimeString: z.string().nullable(),
      actualRunwayDepartureTime: z.number().nullable(),
      actualRunwayDepartureTimeString: z.string().nullable(),
    }),
  }),
  positions: z.array(FlightPositionSchema),
  miniTracker: z.object({
    statusName: z.string(),
    flightStatusCode: z.string(),
    utcDepartureTime: z.number(),
    localDepartureTime: z.number(),
    localDepartureTimeString: z.string(),
    isActualDepartureTime: z.boolean(),
    utcArrivalTime: z.number(),
    localArrivalTime: z.number(),
    localArrivalTimeString: z.string(),
    isActualArrivalTime: z.boolean(),
    utcActualRunwayArrivalTime: z.number().nullable(),
    utcActualRunwayDepartureTime: z.number().nullable(),
    totalKilometers: z.number(),
    arrivalAirport: z.string(),
    departureAirport: z.string(),
    kilometersFromDeparture: z.number(),
    kilometersToArrival: z.number(),
  }),
});
